create table headlines (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title varchar
(255) NOT NULL,
    littel_description varchar
(10000) NOT NULL
    );



create table bussiness_news (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title varchar
(255) NOT NULL,
    details varchar
(100000) NOT NULL,
    shares INTEGER
    );




create table sport_news (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title varchar
(255) NOT NULL,
    details varchar
(100000) NOT NULL,
     shares INTEGER
    );



INSERT INTO headlines
    (title, littel_description)
VALUES
    ('head line 1', 'lil description 1'),
    ('head line 2', 'lil description 2'),
    ('head line 3', 'lil description 3'),
    ('head line 4', 'lil description 4'),
    ('head line 5', 'lil description 5'),
    ('head line 6', 'lil description 6');



INSERT INTO bussiness_news
    (title, details, shares)
VALUES
    ('bussines title 1', 'details 1', 300),
    ('bussines title 2', 'details 2', 300),
    ('bussines title 3', 'details 3', 300),
    ('bussines title 4', 'details 4', 300),
    ('bussines title 5', 'details 5', 300),
    ('bussines title 6', 'details 6', 300);


INSERT INTO sport_news
    (title, details, shares)
VALUES
    ('sport title 1', 'details 1', 400),
    ('sport title 2', 'details 2', 400),
    ('sport title 3', 'details 3', 400),
    ('sport title 4', 'details 4', 400),
    ('sport title 5', 'details 5', 400),
    ('sport title 6', 'details 6', 400);
